const allStatements = [
{"id":1,"pair":1,"type":"premise_1","text":"All dolls are man made","form":"Darii","validity":"valid","plausibility":"plausible"},
{"id":2,"pair":1,"type":"premise_2","text":"Some toys are dolls","form":"Darii","validity":"valid","plausibility":"plausible"},
{"id":3,"pair":1,"type":"conclusion","text":"Some toys are man made","form":"Darii","validity":"valid","plausibility":"plausible"},
{"id":4,"pair":1,"type":"premise_1","text":"All dolls have brown hair","form":"Darii","validity":"valid","plausibility":"implausible"},
{"id":5,"pair":1,"type":"premise_2","text":"Some trucks are dolls","form":"Darii","validity":"valid","plausibility":"implausible"},
{"id":6,"pair":1,"type":"conclusion","text":"Some trucks have brown hair","form":"Darii","validity":"valid","plausibility":"implausible"},
{"id":7,"pair":3,"type":"premise_1","text":"All singers are vocalists","form":"Darii","validity":"valid","plausibility":"plausible"},
{"id":8,"pair":3,"type":"premise_2","text":"Some guitarists are singers","form":"Darii","validity":"valid","plausibility":"plausible"},
{"id":9,"pair":3,"type":"conclusion","text":"Some guitarists are vocalists","form":"Darii","validity":"valid","plausibility":"plausible"},
{"id":10,"pair":3,"type":"premise_1","text":"All guitarists are baritones","form":"Darii","validity":"valid","plausibility":"implausible"},
{"id":11,"pair":3,"type":"premise_2","text":"Some piccolos are guitarists","form":"Darii","validity":"valid","plausibility":"implausible"},
{"id":12,"pair":3,"type":"conclusion","text":"Some piccolos are baritones","form":"Darii","validity":"valid","plausibility":"implausible"},
{"id":13,"pair":5,"type":"premise_1","text":"All poets are writers","form":"Datisi","validity":"valid","plausibility":"plausible"},
{"id":14,"pair":5,"type":"premise_2","text":"Some poets are teachers","form":"Datisi","validity":"valid","plausibility":"plausible"},
{"id":15,"pair":5,"type":"conclusion","text":"Some teachers are writers","form":"Datisi","validity":"valid","plausibility":"plausible"},
{"id":16,"pair":5,"type":"premise_1","text":"All school teachers are authors","form":"Datisi","validity":"valid","plausibility":"implausible"},
{"id":17,"pair":5,"type":"premise_2","text":"Some school teachers are illiterate","form":"Datisi","validity":"valid","plausibility":"implausible"},
{"id":18,"pair":5,"type":"conclusion","text":"Some authors are illiterate","form":"Datisi","validity":"valid","plausibility":"implausible"},
{"id":19,"pair":7,"type":"premise_1","text":"All ponies neigh","form":"Datisi","validity":"valid","plausibility":"plausible"},
{"id":20,"pair":7,"type":"premise_2","text":"Some ponies are thoroughbreds","form":"Datisi","validity":"valid","plausibility":"plausible"},
{"id":21,"pair":7,"type":"conclusion","text":"Some thoroughbreds neigh","form":"Datisi","validity":"valid","plausibility":"plausible"},
{"id":22,"pair":7,"type":"premise_1","text":"All horses are ponies","form":"Datisi","validity":"valid","plausibility":"implausible"},
{"id":23,"pair":7,"type":"premise_2","text":"Some horses are crawlers","form":"Datisi","validity":"valid","plausibility":"implausible"},
{"id":24,"pair":7,"type":"conclusion","text":"Some crawlers are ponies","form":"Datisi","validity":"valid","plausibility":"implausible"},
{"id":25,"pair":9,"type":"premise_1","text":"Some criminals are liars","form":"Dimatis","validity":"valid","plausibility":"plausible"},
{"id":26,"pair":9,"type":"premise_2","text":"All liars are humans","form":"Dimatis","validity":"valid","plausibility":"plausible"},
{"id":27,"pair":9,"type":"conclusion","text":"Some humans are criminals","form":"Dimatis","validity":"valid","plausibility":"plausible"},
{"id":28,"pair":9,"type":"premise_1","text":"Some infants are liars","form":"Dimatis","validity":"valid","plausibility":"implausible"},
{"id":29,"pair":9,"type":"premise_2","text":"All liars are felons","form":"Dimatis","validity":"valid","plausibility":"implausible"},
{"id":30,"pair":9,"type":"conclusion","text":"Some felons are infants","form":"Dimatis","validity":"valid","plausibility":"implausible"},
{"id":31,"pair":11,"type":"premise_1","text":"Some parents are widows","form":"Dimatis","validity":"valid","plausibility":"plausible"},
{"id":32,"pair":11,"type":"premise_2","text":"All widows are women","form":"Dimatis","validity":"valid","plausibility":"plausible"},
{"id":33,"pair":11,"type":"conclusion","text":"Some women are parents","form":"Dimatis","validity":"valid","plausibility":"plausible"},
{"id":34,"pair":11,"type":"premise_1","text":"Some widows are infants","form":"Dimatis","validity":"valid","plausibility":"implausible"},
{"id":35,"pair":11,"type":"premise_2","text":"All infants are men","form":"Dimatis","validity":"valid","plausibility":"implausible"},
{"id":36,"pair":11,"type":"conclusion","text":"Some men are widows","form":"Dimatis","validity":"valid","plausibility":"implausible"},
{"id":37,"pair":13,"type":"premise_1","text":"Some grapes are red","form":"Disamis","validity":"valid","plausibility":"plausible"},
{"id":38,"pair":13,"type":"premise_2","text":"All grapes are fruits","form":"Disamis","validity":"valid","plausibility":"plausible"},
{"id":39,"pair":13,"type":"conclusion","text":"Some fruits are red","form":"Disamis","validity":"valid","plausibility":"plausible"},
{"id":40,"pair":13,"type":"premise_1","text":"Some fruits are carrots","form":"Disamis","validity":"valid","plausibility":"implausible"},
{"id":41,"pair":13,"type":"premise_2","text":"All fruits are wheat","form":"Disamis","validity":"valid","plausibility":"implausible"},
{"id":42,"pair":13,"type":"conclusion","text":"Some wheat is carrots","form":"Disamis","validity":"valid","plausibility":"implausible"},
{"id":43,"pair":15,"type":"premise_1","text":"Some burgers are overcooked","form":"Disamis","validity":"valid","plausibility":"plausible"},
{"id":44,"pair":15,"type":"premise_2","text":"All burgers are sandwiches","form":"Disamis","validity":"valid","plausibility":"plausible"},
{"id":45,"pair":15,"type":"conclusion","text":"Some sandwiches are overcooked","form":"Disamis","validity":"valid","plausibility":"plausible"},
{"id":46,"pair":15,"type":"premise_1","text":"Some sandwiches are beverages","form":"Disamis","validity":"valid","plausibility":"implausible"},
{"id":47,"pair":15,"type":"premise_2","text":"All sandwiches are hamburgers","form":"Disamis","validity":"valid","plausibility":"implausible"},
{"id":48,"pair":15,"type":"conclusion","text":"Some hamburgers are beverages","form":"Disamis","validity":"valid","plausibility":"implausible"},
{"id":49,"pair":17,"type":"premise_1","text":"All vocalists are singers","form":"Darii","validity":"invalid","plausibility":"plausible"},
{"id":50,"pair":17,"type":"premise_2","text":"Some guitarists are singers","form":"Darii","validity":"invalid","plausibility":"plausible"},
{"id":51,"pair":17,"type":"conclusion","text":"Some guitarists are vocalists","form":"Darii","validity":"invalid","plausibility":"plausible"},
{"id":52,"pair":17,"type":"premise_1","text":"All vocalists are guitarists","form":"Darii","validity":"invalid","plausibility":"implausible"},
{"id":53,"pair":17,"type":"premise_2","text":"Some piccolos are guitarists","form":"Darii","validity":"invalid","plausibility":"implausible"},
{"id":54,"pair":17,"type":"conclusion","text":"Some piccolos are vocalists","form":"Darii","validity":"invalid","plausibility":"implausible"},
{"id":55,"pair":19,"type":"premise_1","text":"All suit pieces are made from fabric","form":"Darii","validity":"invalid","plausibility":"plausible"},
{"id":56,"pair":19,"type":"premise_2","text":"Some shirts are made from fabric","form":"Darii","validity":"invalid","plausibility":"plausible"},
{"id":57,"pair":19,"type":"conclusion","text":"Some shirts are suit pieces","form":"Darii","validity":"invalid","plausibility":"plausible"},
{"id":58,"pair":19,"type":"premise_1","text":"All shirts are suits","form":"Darii","validity":"invalid","plausibility":"implausible"},
{"id":59,"pair":19,"type":"premise_2","text":"Some shoes are suits","form":"Darii","validity":"invalid","plausibility":"implausible"},
{"id":60,"pair":19,"type":"conclusion","text":"Some shoes are shirts","form":"Darii","validity":"invalid","plausibility":"implausible"},
{"id":61,"pair":21,"type":"premise_1","text":"All chili dogs are hotdogs","form":"Datisi","validity":"invalid","plausibility":"plausible"},
{"id":62,"pair":21,"type":"premise_2","text":"Some hotdogs are grilled","form":"Datisi","validity":"invalid","plausibility":"plausible"},
{"id":63,"pair":21,"type":"conclusion","text":"Some grilled things are chili dogs","form":"Datisi","validity":"invalid","plausibility":"plausible"},
{"id":64,"pair":21,"type":"premise_1","text":"All hotdogs are chilidogs","form":"Datisi","validity":"invalid","plausibility":"implausible"},
{"id":65,"pair":21,"type":"premise_2","text":"Some chilidogs are tacos","form":"Datisi","validity":"invalid","plausibility":"implausible"},
{"id":66,"pair":21,"type":"conclusion","text":"Some tacos are hotdogs","form":"Datisi","validity":"invalid","plausibility":"implausible"},
{"id":67,"pair":23,"type":"premise_1","text":"All paintings are framed","form":"Datisi","validity":"invalid","plausibility":"plausible"},
{"id":68,"pair":23,"type":"premise_2","text":"Some framed things are portraits","form":"Datisi","validity":"invalid","plausibility":"plausible"},
{"id":69,"pair":23,"type":"conclusion","text":"Some portraits are paintings","form":"Datisi","validity":"invalid","plausibility":"plausible"},
{"id":70,"pair":23,"type":"premise_1","text":"All sculptures are paintings","form":"Datisi","validity":"invalid","plausibility":"implausible"},
{"id":71,"pair":23,"type":"premise_2","text":"Some paintings are produce audio","form":"Datisi","validity":"invalid","plausibility":"implausible"},
{"id":72,"pair":23,"type":"conclusion","text":"Some things that produce audio are sculptures","form":"Datisi","validity":"invalid","plausibility":"implausible"},
{"id":73,"pair":25,"type":"premise_1","text":"Some bags are pieces of luggage","form":"Dimatis","validity":"invalid","plausibility":"plausible"},
{"id":74,"pair":25,"type":"premise_2","text":"All suitcases are pieces of luggage","form":"Dimatis","validity":"invalid","plausibility":"plausible"},
{"id":75,"pair":25,"type":"conclusion","text":"Some suitcases are bags","form":"Dimatis","validity":"invalid","plausibility":"plausible"},
{"id":76,"pair":25,"type":"premise_1","text":"Some passengers are luggage","form":"Dimatis","validity":"invalid","plausibility":"implausible"},
{"id":77,"pair":25,"type":"premise_2","text":"All bags are luggage","form":"Dimatis","validity":"invalid","plausibility":"implausible"},
{"id":78,"pair":25,"type":"conclusion","text":"Some bags are passengers","form":"Dimatis","validity":"invalid","plausibility":"implausible"},
{"id":79,"pair":27,"type":"premise_1","text":"Some buildings are workspaces","form":"Dimatis","validity":"invalid","plausibility":"plausible"},
{"id":80,"pair":27,"type":"premise_2","text":"All offices are workspaces","form":"Dimatis","validity":"invalid","plausibility":"plausible"},
{"id":81,"pair":27,"type":"conclusion","text":"Some offices are buildings","form":"Dimatis","validity":"invalid","plausibility":"plausible"},
{"id":82,"pair":27,"type":"premise_1","text":"Some beaches are offices","form":"Dimatis","validity":"invalid","plausibility":"implausible"},
{"id":83,"pair":27,"type":"premise_2","text":"All rooms are offices","form":"Dimatis","validity":"invalid","plausibility":"implausible"},
{"id":84,"pair":27,"type":"conclusion","text":"Some rooms are beaches","form":"Dimatis","validity":"invalid","plausibility":"implausible"},
{"id":85,"pair":29,"type":"premise_1","text":"Some paths are straight","form":"Disamis","validity":"invalid","plausibility":"plausible"},
{"id":86,"pair":29,"type":"premise_2","text":"All roads are paths","form":"Disamis","validity":"invalid","plausibility":"plausible"},
{"id":87,"pair":29,"type":"conclusion","text":"Some roads are straight","form":"Disamis","validity":"invalid","plausibility":"plausible"},
{"id":88,"pair":29,"type":"premise_1","text":"Some gravel is buoyant","form":"Disamis","validity":"invalid","plausibility":"implausible"},
{"id":89,"pair":29,"type":"premise_2","text":"All roads are gravel","form":"Disamis","validity":"invalid","plausibility":"implausible"},
{"id":90,"pair":29,"type":"conclusion","text":"Some roads are buoyant","form":"Disamis","validity":"invalid","plausibility":"implausible"},
{"id":91,"pair":31,"type":"premise_1","text":"Some chairs have four legs","form":"Disamis","validity":"invalid","plausibility":"plausible"},
{"id":92,"pair":31,"type":"premise_2","text":"All things you can sit in are chairs","form":"Disamis","validity":"invalid","plausibility":"plausible"},
{"id":93,"pair":31,"type":"conclusion","text":"Some things you can sit in have four legs","form":"Disamis","validity":"invalid","plausibility":"plausible"},
{"id":94,"pair":31,"type":"premise_1","text":"Some couches are liquid","form":"Disamis","validity":"invalid","plausibility":"implausible"},
{"id":95,"pair":31,"type":"premise_2","text":"All chairs are couches","form":"Disamis","validity":"invalid","plausibility":"implausible"},
{"id":96,"pair":31,"type":"conclusion","text":"Some chairs are liquid","form":"Disamis","validity":"invalid","plausibility":"implausible"},
{"id":97,"pair":2,"type":"premise_1","text":"All doughnuts are sugary","form":"Darii","validity":"valid","plausibility":"plausible"},
{"id":98,"pair":2,"type":"premise_2","text":"Some pastries are doughnuts","form":"Darii","validity":"valid","plausibility":"plausible"},
{"id":99,"pair":2,"type":"conclusion","text":"Some pastries are sugary","form":"Darii","validity":"valid","plausibility":"plausible"},
{"id":100,"pair":2,"type":"premise_1","text":"All doughnuts are cakes","form":"Darii","validity":"valid","plausibility":"implausible"},
{"id":101,"pair":2,"type":"premise_2","text":"Some crackers are doughnuts","form":"Darii","validity":"valid","plausibility":"implausible"},
{"id":102,"pair":2,"type":"conclusion","text":"Some crackers are cake","form":"Darii","validity":"valid","plausibility":"implausible"},
{"id":103,"pair":4,"type":"premise_1","text":"All clowns can juggle","form":"Darii","validity":"valid","plausibility":"plausible"},
{"id":104,"pair":4,"type":"premise_2","text":"Some circus performers are clowns","form":"Darii","validity":"valid","plausibility":"plausible"},
{"id":105,"pair":4,"type":"conclusion","text":"Some circus performers can juggle","form":"Darii","validity":"valid","plausibility":"plausible"},
{"id":106,"pair":4,"type":"premise_1","text":"All jugglers are clowns","form":"Darii","validity":"valid","plausibility":"implausible"},
{"id":107,"pair":4,"type":"premise_2","text":"Some lions can juggle","form":"Darii","validity":"valid","plausibility":"implausible"},
{"id":108,"pair":4,"type":"conclusion","text":"Some lions are clowns","form":"Darii","validity":"valid","plausibility":"implausible"},
{"id":109,"pair":6,"type":"premise_1","text":"All mugs are cups","form":"Datisi","validity":"valid","plausibility":"plausible"},
{"id":110,"pair":6,"type":"premise_2","text":"Some mugs are ceramics","form":"Datisi","validity":"valid","plausibility":"plausible"},
{"id":111,"pair":6,"type":"conclusion","text":"Some ceramics are cups","form":"Datisi","validity":"valid","plausibility":"plausible"},
{"id":112,"pair":6,"type":"premise_1","text":"All cups are mugs","form":"Datisi","validity":"valid","plausibility":"implausible"},
{"id":113,"pair":6,"type":"premise_2","text":"Some cups are bottles","form":"Datisi","validity":"valid","plausibility":"implausible"},
{"id":114,"pair":6,"type":"conclusion","text":"Some bottles are mugs","form":"Datisi","validity":"valid","plausibility":"implausible"},
{"id":115,"pair":8,"type":"premise_1","text":"All statues are sculptures","form":"Datisi","validity":"valid","plausibility":"plausible"},
{"id":116,"pair":8,"type":"premise_2","text":"Some statues are bronzes","form":"Datisi","validity":"valid","plausibility":"plausible"},
{"id":117,"pair":8,"type":"conclusion","text":"Some bronzes are sculptures","form":"Datisi","validity":"valid","plausibility":"plausible"},
{"id":118,"pair":8,"type":"premise_1","text":"All sculptures are statues","form":"Datisi","validity":"valid","plausibility":"implausible"},
{"id":119,"pair":8,"type":"premise_2","text":"Some sculptures are graffiti","form":"Datisi","validity":"valid","plausibility":"implausible"},
{"id":120,"pair":8,"type":"conclusion","text":"Some graffiti are statues","form":"Datisi","validity":"valid","plausibility":"implausible"},
{"id":121,"pair":10,"type":"premise_1","text":"Some cars are trucks","form":"Dimatis","validity":"valid","plausibility":"plausible"},
{"id":122,"pair":10,"type":"premise_2","text":"All trucks are vehicles","form":"Dimatis","validity":"valid","plausibility":"plausible"},
{"id":123,"pair":10,"type":"conclusion","text":"Some vehicles are cars","form":"Dimatis","validity":"valid","plausibility":"plausible"},
{"id":124,"pair":10,"type":"premise_1","text":"Some boats are cars","form":"Dimatis","validity":"valid","plausibility":"implausible"},
{"id":125,"pair":10,"type":"premise_2","text":"All cars are trucks","form":"Dimatis","validity":"valid","plausibility":"implausible"},
{"id":126,"pair":10,"type":"conclusion","text":"Some trucks are boats","form":"Dimatis","validity":"valid","plausibility":"implausible"},
{"id":127,"pair":12,"type":"premise_1","text":"Some bags are suitcases","form":"Dimatis","validity":"valid","plausibility":"plausible"},
{"id":128,"pair":12,"type":"premise_2","text":"All suitcases are pieces of luggage","form":"Dimatis","validity":"valid","plausibility":"plausible"},
{"id":129,"pair":12,"type":"conclusion","text":"Some pieces of luggage are bags","form":"Dimatis","validity":"valid","plausibility":"plausible"},
{"id":130,"pair":12,"type":"premise_1","text":"Some purses are baskets","form":"Dimatis","validity":"valid","plausibility":"implausible"},
{"id":131,"pair":12,"type":"premise_2","text":"All baskets are purses","form":"Dimatis","validity":"valid","plausibility":"implausible"},
{"id":132,"pair":12,"type":"conclusion","text":"Some bags are baskets","form":"Dimatis","validity":"valid","plausibility":"implausible"},
{"id":133,"pair":14,"type":"premise_1","text":"Some swords are decorative","form":"Disamis","validity":"valid","plausibility":"plausible"},
{"id":134,"pair":14,"type":"premise_2","text":"All swords are weapons","form":"Disamis","validity":"valid","plausibility":"plausible"},
{"id":135,"pair":14,"type":"conclusion","text":"Some weapons are decorative","form":"Disamis","validity":"valid","plausibility":"plausible"},
{"id":136,"pair":14,"type":"premise_1","text":"Some weapons are healing","form":"Disamis","validity":"valid","plausibility":"implausible"},
{"id":137,"pair":14,"type":"premise_2","text":"All weapons are swords","form":"Disamis","validity":"valid","plausibility":"implausible"},
{"id":138,"pair":14,"type":"conclusion","text":"Some swords are healing","form":"Disamis","validity":"valid","plausibility":"implausible"},
{"id":139,"pair":16,"type":"premise_1","text":"Some rifles are for hunting","form":"Disamis","validity":"valid","plausibility":"plausible"},
{"id":140,"pair":16,"type":"premise_2","text":"All rifles are guns","form":"Disamis","validity":"valid","plausibility":"plausible"},
{"id":141,"pair":16,"type":"conclusion","text":"Some guns are for hunting","form":"Disamis","validity":"valid","plausibility":"plausible"},
{"id":142,"pair":16,"type":"premise_1","text":"Some guns are bullets","form":"Disamis","validity":"valid","plausibility":"implausible"},
{"id":143,"pair":16,"type":"premise_2","text":"All guns are rifles","form":"Disamis","validity":"valid","plausibility":"implausible"},
{"id":144,"pair":16,"type":"conclusion","text":"Some rifles are bullets","form":"Disamis","validity":"valid","plausibility":"implausible"},
{"id":145,"pair":18,"type":"premise_1","text":"All computers run code","form":"Darii","validity":"invalid","plausibility":"plausible"},
{"id":146,"pair":18,"type":"premise_2","text":"Some calculators run code","form":"Darii","validity":"invalid","plausibility":"plausible"},
{"id":147,"pair":18,"type":"conclusion","text":"Some calculators are computers","form":"Darii","validity":"invalid","plausibility":"plausible"},
{"id":148,"pair":18,"type":"premise_1","text":"All devices are computers","form":"Darii","validity":"invalid","plausibility":"implausible"},
{"id":149,"pair":18,"type":"premise_2","text":"Some keyboards are computers","form":"Darii","validity":"invalid","plausibility":"implausible"},
{"id":150,"pair":18,"type":"conclusion","text":"Some keyboards are devices","form":"Darii","validity":"invalid","plausibility":"implausible"},
{"id":151,"pair":20,"type":"premise_1","text":"All baby chicks have down","form":"Darii","validity":"invalid","plausibility":"plausible"},
{"id":152,"pair":20,"type":"premise_2","text":"Some birds have down","form":"Darii","validity":"invalid","plausibility":"plausible"},
{"id":153,"pair":20,"type":"conclusion","text":"Some birds are baby chicks","form":"Darii","validity":"invalid","plausibility":"plausible"},
{"id":154,"pair":20,"type":"premise_1","text":"All baby chicks have fur","form":"Darii","validity":"invalid","plausibility":"implausible"},
{"id":155,"pair":20,"type":"premise_2","text":"Some reptiles have fur","form":"Darii","validity":"invalid","plausibility":"implausible"},
{"id":156,"pair":20,"type":"conclusion","text":"Some reptiles are baby chicks","form":"Darii","validity":"invalid","plausibility":"implausible"},
{"id":157,"pair":22,"type":"premise_1","text":"All pens are writing utensils","form":"Datisi","validity":"invalid","plausibility":"plausible"},
{"id":158,"pair":22,"type":"premise_2","text":"Some writing utensils use black ink","form":"Datisi","validity":"invalid","plausibility":"plausible"},
{"id":159,"pair":22,"type":"conclusion","text":"Some things that use black ink are pens","form":"Datisi","validity":"invalid","plausibility":"plausible"},
{"id":160,"pair":22,"type":"premise_1","text":"All pens are markers","form":"Datisi","validity":"invalid","plausibility":"implausible"},
{"id":161,"pair":22,"type":"premise_2","text":"Some markers are lighters","form":"Datisi","validity":"invalid","plausibility":"implausible"},
{"id":162,"pair":22,"type":"conclusion","text":"Some lighters are pens","form":"Datisi","validity":"invalid","plausibility":"implausible"},
{"id":163,"pair":24,"type":"premise_1","text":"All speakers are hardware","form":"Datisi","validity":"invalid","plausibility":"plausible"},
{"id":164,"pair":24,"type":"premise_2","text":"Some hardware produces audio","form":"Datisi","validity":"invalid","plausibility":"plausible"},
{"id":165,"pair":24,"type":"conclusion","text":"Some speakers produce audio","form":"Datisi","validity":"invalid","plausibility":"plausible"},
{"id":166,"pair":24,"type":"premise_1","text":"All speakers are subwoofers","form":"Datisi","validity":"invalid","plausibility":"implausible"},
{"id":167,"pair":24,"type":"premise_2","text":"Some subwoofers are drum sets","form":"Datisi","validity":"invalid","plausibility":"implausible"},
{"id":168,"pair":24,"type":"conclusion","text":"Some speakers are drum sets","form":"Datisi","validity":"invalid","plausibility":"implausible"},
{"id":169,"pair":26,"type":"premise_1","text":"Some criminals are liars","form":"Dimatis","validity":"invalid","plausibility":"plausible"},
{"id":170,"pair":26,"type":"premise_2","text":"All humans are liars","form":"Dimatis","validity":"invalid","plausibility":"plausible"},
{"id":171,"pair":26,"type":"conclusion","text":"Some humans are criminals","form":"Dimatis","validity":"invalid","plausibility":"plausible"},
{"id":172,"pair":26,"type":"premise_1","text":"Some judges are liars","form":"Dimatis","validity":"invalid","plausibility":"implausible"},
{"id":173,"pair":26,"type":"premise_2","text":"All liars are criminals","form":"Dimatis","validity":"invalid","plausibility":"implausible"},
{"id":174,"pair":26,"type":"conclusion","text":"Some criminals are judges","form":"Dimatis","validity":"invalid","plausibility":"implausible"},
{"id":175,"pair":28,"type":"premise_1","text":"Some desserts are sweet","form":"Dimatis","validity":"invalid","plausibility":"plausible"},
{"id":176,"pair":28,"type":"premise_2","text":"All candy is sweet","form":"Dimatis","validity":"invalid","plausibility":"plausible"},
{"id":177,"pair":28,"type":"conclusion","text":"Some candy is dessert","form":"Dimatis","validity":"invalid","plausibility":"plausible"},
{"id":178,"pair":28,"type":"premise_1","text":"Some anchovies are candy","form":"Dimatis","validity":"invalid","plausibility":"implausible"},
{"id":179,"pair":28,"type":"premise_2","text":"All sweet snacks are candy","form":"Dimatis","validity":"invalid","plausibility":"implausible"},
{"id":180,"pair":28,"type":"conclusion","text":"Some sweet snacks are anchovies","form":"Dimatis","validity":"invalid","plausibility":"implausible"},
{"id":181,"pair":30,"type":"premise_1","text":"Some footwear are high heels","form":"Disamis","validity":"invalid","plausibility":"plausible"},
{"id":182,"pair":30,"type":"premise_2","text":"All shoes are footwear","form":"Disamis","validity":"invalid","plausibility":"plausible"},
{"id":183,"pair":30,"type":"conclusion","text":"Some shoes are high heels","form":"Disamis","validity":"invalid","plausibility":"plausible"},
{"id":184,"pair":30,"type":"premise_1","text":"Some sandals are living","form":"Disamis","validity":"invalid","plausibility":"implausible"},
{"id":185,"pair":30,"type":"premise_2","text":"All shoes are sandals","form":"Disamis","validity":"invalid","plausibility":"implausible"},
{"id":186,"pair":30,"type":"conclusion","text":"Some shoes are living","form":"Disamis","validity":"invalid","plausibility":"implausible"},
{"id":187,"pair":32,"type":"premise_1","text":"Some containers are glasses","form":"Disamis","validity":"invalid","plausibility":"plausible"},
{"id":188,"pair":32,"type":"premise_2","text":"All cups are containers","form":"Disamis","validity":"invalid","plausibility":"plausible"},
{"id":189,"pair":32,"type":"conclusion","text":"Some cups are glasses","form":"Disamis","validity":"invalid","plausibility":"plausible"},
{"id":190,"pair":32,"type":"premise_1","text":"Some cups are napkins","form":"Disamis","validity":"invalid","plausibility":"implausible"},
{"id":191,"pair":32,"type":"premise_2","text":"All containers are cups","form":"Disamis","validity":"invalid","plausibility":"implausible"},
{"id":192,"pair":32,"type":"conclusion","text":"Some containers are napkins","form":"Disamis","validity":"invalid","plausibility":"implausible"},
{"id":193,"pair":33,"type":"premise_1","text":"Philadelphia is in Pennsylvania","form":"Sunny","validity":"invalid","plausibility":"implausible"},	
{"id":194,"pair":33,"type":"premise_2","text":"Pittsburgh is in Pennsylvania","form":"Sunny","validity":"invalid","plausibility":"implausible"},
{"id":195,"pair":33,"type":"conclusion","text":"Pittsburgh is in Philadelphia","form":"Sunny","validity":"invalid","plausibility":"implausible"},
{"id":196,"pair":33,"type":"premise_1","text":"Pittsburgh is in Pennsylvania","form":"Sunny","validity":"valid","plausibility":"plausible"},
{"id":197,"pair":33,"type":"premise_2","text":"Pennsylvania is in the United States","form":"Sunny","validity":"valid","plausibility":"plausible"},
{"id":198,"pair":33,"type":"conclusion","text":"Pittsburgh is in the United States","form":"Sunny","validity":"valid","plausibility":"plausible"},
{"id":199,"pair":34,"type":"premise_1","text":"Austin is in the United States","form":"Sunny","validity":"invalid","plausibility":"plausible"},
{"id":200,"pair":34,"type":"premise_2","text":"Texas is in the United States","form":"Sunny","validity":"invalid","plausibility":"plausible"},
{"id":201,"pair":34,"type":"conclusion","text":"Austin is in Texas","form":"Sunny","validity":"invalid","plausibility":"plausible"},
{"id":202,"pair":34,"type":"premise_1","text":"The Vatican is in Nevada","form":"Sunny","validity":"valid","plausibility":"implausible"},
{"id":203,"pair":34,"type":"premise_2","text":"Nevada is in Hawaii","form":"Sunny","validity":"valid","plausibility":"implausible"},
{"id":204,"pair":34,"type":"conclusion","text":"The Vatican is in Hawaii","form":"Sunny","validity":"valid","plausibility":"implausible"},

{"id":205, "type":"attention","text":"Madison is in Wisconsin","plausibility":"plausible"},
{"id":206, "type":"attention","text":"Madison is in Wisconsin","plausibility":"plausible"},
{"id":207, "type":"attention","text":"The sky is blue","plausibility":"plausible"},
{"id":208, "type":"attention","text":"The sky is blue","plausibility":"plausible"},
{"id":209, "type":"attention","text":"One plus one is three","plausibility":"plausible"},
{"id":210, "type":"attention","text":"One plus one is three","plausibility":"plausible"},
{"id":211, "type":"attention","text":"The sun orbits the earth","plausibility":"plausible"},
{"id":212, "type":"attention","text":"The sun orbits the earth","plausibility":"plausible"},
{"id":213, "type":"attention","text":"The squank is garb"},
{"id":214, "type":"attention","text":"The squank is garb"},
{"id":215, "type":"attention","text":"The fwitch is snorg"},
{"id":216, "type":"attention","text":"The fwitch is snorg"}
];
